# Generated by Django 5.0.14 on 2026-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
    ]
