# Generated by Django 5.0.6 on 2026-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
